shellrc: add function to regenerate GPG shadow keys
Signed-off-by: Antoine Damhet <antoine.damhet@lse.epita.fr>

diff --git a/shellrc b/shellrc
--- a/shellrc
+++ b/shellrc
@@ -44,6 +44,22 @@ function compress() {
 	fi
 }
 
+function reshadow() {
+	local keydir="$(gpgconf --list-dirs homedir)/private-keys-v1.d"
+	if [ -d "${keydir}" ]; then
+		for key in $(find ${keydir} -name \*.key); do
+			if [ "$(head -c 24 $key | tail -c 20)" = "shadowed-private-key" ]; then
+				rm -f "$key"
+			fi
+		done
+		gpg --card-status &> /dev/null
+		echo "Done"
+	else
+		echo "GPG keydir not found" >&2
+		return 1
+	fi
+}
+
 # Ls colors
 if [ -x /usr/bin/dircolors ]; then
 	if [ -r $HOME/.dir_colors ]; then
